name: CI - Build Static Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      BACKEND_URL: ${{ secrets.BACKEND_URL }}
    
    outputs:
      build_version: ${{ steps.version.outputs.build_version }}
      build_artifact: ${{ steps.upload.outputs.artifact_name }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate Build Version
        id: version
        run: echo "build_version=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
      
      - name: Create env file
        run: |
          echo "VITE_BACKENDURL=$BACKEND_URL" > .env.local
          echo "REACT_APP_BUILD_VERSION=${{ steps.version.outputs.build_version }}" >> .env.local
      
      - name: Build static site
        run: npm run build
      
      - name: Upload build artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: static-site-build
          path: ./dist
          retention-days: 30
      
      - name: Save build version to file
        run: echo "${{ steps.version.outputs.build_version }}" > build_version.txt
      
      - name: Upload build version
        uses: actions/upload-artifact@v4
        with:
          name: build-version
          path: build_version.txt
          retention-days: 30