name: CI - Build Static Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BACKEND_URL: ${{ secrets.BACKEND_URL }}

    outputs:
      build_version: ${{ steps.version.outputs.build_version }}
      build_artifact: ${{ steps.upload.outputs.artifact_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Generate Build Version
        id: version
        run: echo "::set-output name=build_version::$(date +%Y%m%d%H%M%S)"

      - name: Create env file
        run: |
          echo "VITE_BACKENDURL=$BACKEND_URL" > .env.local
          echo "REACT_APP_BUILD_VERSION=${{ steps.version.outputs.build_version }}" >> .env.local

      - name: Build static site
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-site-build-${{ steps.get_version.outputs.build_version }}
          path: ./dist


