name: CI - Build Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Required permissions for OIDC authentication
permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: '20'
  TERRAFORM_VERSION: '1.6.0'
  WORKING_DIRECTORY: './terraform'
  BUILD_ARTIFACT_PATH: './dist'

jobs:
  build:
    name: 'Build Application'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Verify build output
      run: |
        echo "Checking build output..."
        if [ -d "./dist" ]; then
          echo "Build directory exists"
          ls -la ./dist/
        else
          echo "ERROR: Build directory not found!"
          exit 1
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ./dist/
        retention-days: 30
        if-no-files-found: error

  terraform:
    name: 'Terraform Infrastructure'
    runs-on: ubuntu-latest
    needs: build
    environment: production
    outputs:
      storage_account_link: ${{ steps.terraform_output.outputs.storage_account_link }}
      storage_account_name: ${{ steps.terraform_output.outputs.storage_account_name }}
      resource_group_name: ${{ steps.terraform_output.outputs.resource_group_name }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # OIDC Login - No client secret needed
    - name: Azure Login via OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        terraform_wrapper: false

    - name: Terraform Init
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_USE_OIDC: true
      run: terraform init

    - name: Terraform Validate
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_USE_OIDC: true
      run: terraform validate

    - name: Terraform Plan
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_USE_OIDC: true
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_USE_OIDC: true
      run: terraform apply -auto-approve tfplan

    - name: Get Terraform Outputs
      id: terraform_output
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_USE_OIDC: true
      run: |
        echo "storage_account_link=$(terraform output -raw storage_account_link)" >> $GITHUB_OUTPUT
        echo "storage_account_name=$(terraform output -raw storage_account_name)" >> $GITHUB_OUTPUT
        echo "resource_group_name=$(terraform output -raw resource_group_name)" >> $GITHUB_OUTPUT

  deploy:
    name: 'Deploy to Azure Storage'
    runs-on: ubuntu-latest
    needs: [build, terraform]
    environment: production
    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: ${{ env.BUILD_ARTIFACT_PATH }}

    - name: Verify artifacts downloaded
      run: |
        echo "Checking downloaded artifacts..."
        if [ -d "${{ env.BUILD_ARTIFACT_PATH }}" ]; then
          echo "Build directory exists after download"
          ls -la ${{ env.BUILD_ARTIFACT_PATH }}
          if [ -z "$(ls -A ${{ env.BUILD_ARTIFACT_PATH }})" ]; then
            echo "ERROR: Build directory is empty!"
            exit 1
          fi
        else
          echo "ERROR: Build directory not found after download!"
          exit 1
        fi

    # OIDC Login - No client secret needed
    - name: Azure Login via OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Upload to Azure Storage
      run: |
        echo "Uploading files to storage account: ${{ needs.terraform.outputs.storage_account_name }}"
        az storage blob upload-batch \
          --account-name ${{ needs.terraform.outputs.storage_account_name }} \
          --destination '$web' \
          --source ${{ env.BUILD_ARTIFACT_PATH }} \
          --overwrite \
          --auth-mode login

    - name: Display Website URL
      run: |
        echo "Website deployed to: ${{ needs.terraform.outputs.storage_account_link }}"